version: "2"

services:
    dev:
        image: node:argon
        environment:
            VIRTUAL_PORT: 80
        expose:
            - "80"
        command: npm run dev
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        # Configure ports in docker-compose.override.yml
        # ports:
        #     - "80:80"
